// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo69uStzDg-jvM0eWAiCAkacn--OIts0I',
    appId: '1:90651931137:web:eb849dc0956dba2192c600',
    messagingSenderId: '90651931137',
    projectId: 'lista-2bed3',
    authDomain: 'lista-2bed3.firebaseapp.com',
    storageBucket: 'lista-2bed3.firebasestorage.app',
    measurementId: 'G-F9VC9FJLRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCbc1t58GOPI8-FnZ0adFvgHSQo-rsiDs',
    appId: '1:90651931137:android:1b40ec862fe9786b92c600',
    messagingSenderId: '90651931137',
    projectId: 'lista-2bed3',
    storageBucket: 'lista-2bed3.firebasestorage.app',
  );
}
